sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '6'
before_script:
  - yarn global add codecov
script:
  - npm test
  - npm run format
after_success:
  - codecov
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    